-- =====================================================
-- ENTERPRISE SEARCH ENGINE v2 - DOCUMENTATION
-- Applied to: Supabase project bgwfyumunybbdthgykoh
-- Last updated: 2026-02-23
-- =====================================================

-- ARCHITECTURE:
-- Two-phase, server-side, deterministic-ranking search engine
-- Implemented as PostgreSQL RPC function
-- Frontend calls via supabase.rpc('search_products', ...)

-- EXTENSIONS USED:
-- pg_trgm (trigram similarity for fallback LIKE matching)
-- unaccent (future accent-insensitive support)

-- SCHEMA ADDITIONS:
-- products.search_vector (tsvector) - auto-maintained via trigger
-- products.normalized_description (text) - auto-maintained via trigger (lower(brand + model))

-- INDEXES CREATED:
-- idx_products_search_vector         GIN(search_vector)
-- idx_products_imei1                 B-tree(imei1) WHERE NOT NULL
-- idx_products_imei2                 B-tree(imei2) WHERE NOT NULL
-- idx_products_serial                B-tree("serialNumber") WHERE NOT NULL
-- idx_products_model_trgm            GIN(model gin_trgm_ops)
-- idx_products_stock                 B-tree(stock)
-- idx_products_created_at            B-tree("createdAt" DESC)
-- idx_products_normalized_desc       B-tree(normalized_description)
-- idx_products_normalized_desc_trgm  GIN(normalized_description gin_trgm_ops)
-- idx_products_created_stock         B-tree("createdAt" DESC, stock)

-- FUNCTION SIGNATURE:
-- search_products(
--   p_query text,              -- search query (can be empty for browsing)
--   p_stock_filter text,       -- 'in_stock', 'out_of_stock', 'all'
--   p_condition_filter text,   -- 'Todos', 'Novo', 'Seminovo', etc.
--   p_location_filter text,    -- 'Todos' or specific location
--   p_type_filter text,        -- 'Todos', 'Produtos Apple', 'Produtos Variados', etc.
--   p_sort_order text,         -- 'relevance', 'newest', 'oldest'
--   p_limit int,               -- pagination limit (default 15)  
--   p_offset int               -- pagination offset (default 0)
-- )

-- EXECUTION PHASES:
--
-- PHASE 0: Input Normalization
--   - lower(), trim(), collapse spaces
--   - Tokenize into array
--   - Build tsquery with AND logic
--   - Detect IMEI/serial searches (5+ digit numeric)
--
-- PHASE 1: IMEI Fast Path (sub-15ms via B-tree)
--   - If input is 5+ numeric digits
--   - Direct indexed lookup on imei1, imei2, serialNumber
--   - Returns immediately with score=500 if found
--   - Skips Phase 2 entirely
--
-- PHASE 2: Ranked Full-Text Search (7-layer scoring)
--   Uses CTE: candidates → scored → total → paginated output

-- SCORING MODEL (7 LAYERS):
--
-- L1: PHRASE BOOST
--   +200 = Exact phrase in normalized_description
--   +120 = First token appears within first 20 chars
--
-- L2: FULL-TEXT RANK
--   +(ts_rank_cd * 80) = PostgreSQL full-text ranking
--
-- L3: TOKEN COVERAGE (inline, no subquery, up to 8 tokens)
--   +60  = All search tokens present as whole words
--   +20  = SKU exact token match
--
-- L4: CATEGORY INTELLIGENCE
--   +100 = Device categories (iPhone, iPad, Mac, Watch, AirPods, Smartphone, Console)
--   +70  = Unknown/other categories
--   +50  = Accessory categories (Acessórios, Cabo, Fontes, Película, etc.)
--   +40  = Repair parts (Tela, Bateria, LCD, OLED in description)
--
-- L5: STRICT PRO/MAX/ULTRA/PLUS CONTROL
--   -60  = Product has 'pro' but user didn't search 'pro'
--   -25  = Product has 'max' but user didn't search 'max'
--   -20  = Product has 'ultra' but user didn't search 'ultra'
--   -15  = Product has 'plus' but user didn't search 'plus'
--
-- L6: EXTRA TOKEN PENALTY
--   -25/word = For each word in description beyond (search_tokens + 3)
--
-- L7: PREFIX FAILURE PENALTY
--   -40  = First search token not found in description

-- COMMERCIAL BEHAVIOR EXAMPLES:
--
-- Search "17 256gb":
--   1st: iPhone 17 256GB (score ~520) ← exact phrase + device + all tokens
--   2nd: iPhone 17 Pro 256GB (score ~197) ← pro penalty applied (-60)
--   3rd: iPhone 17 Pro Max 256GB (score ~165) ← pro + max penalty (-85 total)
--
-- Search "iphone 14":
--   1st: iPhone 14 128GB devices (score ~520)
--   2nd: Tela LCD iPhone 14 (score ~435) ← accessory category penalty
--   3rd: iPhone 14 Pro 128GB (score ~435) ← pro penalty
--   4th: Bateria Foxconn iPhone 14 (score ~380) ← repair part + extra tokens
--
-- ORDER BY: relevance_score DESC, "createdAt" DESC, id DESC
-- (Fully deterministic. No random ordering. Safe for pagination.)
